In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as snn

In [45]:
df=pd.read_csv(r'C:\Users\hp\Downloads\Admission_Predict.csv')
df

Serial_no  GRE Score  TOEFL Score  University_Rating  SOP  LOR   CGPA  \
0            1        337          118                  4  4.5   4.5  9.65   
1            2        324          107                  4  4.0   4.5  8.87   
2            3        316          104                  3  3.0   3.5  8.00   
3            4        322          110                  3  3.5   2.5  8.67   
4            5        314          103                  2  2.0   3.0  8.21   
..         ...        ...          ...                ...  ...   ...   ...   
395        396        324          110                  3  3.5   3.5  9.04   
396        397        325          107                  3  3.0   3.5  9.11   
397        398        330          116                  4  5.0   4.5  9.45   
398        399        312          103                  3  3.5   4.0  8.78   
399        400        333          117                  4  5.0   4.0  9.66   

     Research  Chance_of_Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
395         1             0.82  
396         1             0.84  
397         1             0.91  
398         0             0.67  
399         1             0.95  

[400 rows x 9 columns]

In [46]:
df.drop('Serial_no',axis=1)

GRE Score  TOEFL Score  University_Rating  SOP  LOR   CGPA  Research  \
0          337          118                  4  4.5   4.5  9.65         1   
1          324          107                  4  4.0   4.5  8.87         1   
2          316          104                  3  3.0   3.5  8.00         1   
3          322          110                  3  3.5   2.5  8.67         1   
4          314          103                  2  2.0   3.0  8.21         0   
..         ...          ...                ...  ...   ...   ...       ...   
395        324          110                  3  3.5   3.5  9.04         1   
396        325          107                  3  3.0   3.5  9.11         1   
397        330          116                  4  5.0   4.5  9.45         1   
398        312          103                  3  3.5   4.0  8.78         0   
399        333          117                  4  5.0   4.0  9.66         1   

     Chance_of_Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
395             0.82  
396             0.84  
397             0.91  
398             0.67  
399             0.95  

[400 rows x 8 columns]

In [47]:
X=df.drop(['Serial_no','Chance_of_Admit'],axis=1)
X

GRE Score  TOEFL Score  University_Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
395        324          110                  3  3.5   3.5  9.04         1
396        325          107                  3  3.0   3.5  9.11         1
397        330          116                  4  5.0   4.5  9.45         1
398        312          103                  3  3.5   4.0  8.78         0
399        333          117                  4  5.0   4.0  9.66         1

[400 rows x 7 columns]

In [48]:
y=df.Chance_of_Admit
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
395    0.82
396    0.84
397    0.91
398    0.67
399    0.95
Name: Chance_of_Admit, Length: 400, dtype: float64

In [49]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()

In [55]:
X = std.fit_transform(X)
X

array([[ 1.76210664,  1.74697064,  0.79882862, ...,  1.16732114,
         1.76481828,  0.90911166],
       [ 0.62765641, -0.06763531,  0.79882862, ...,  1.16732114,
         0.45515126,  0.90911166],
       [-0.07046681, -0.56252785, -0.07660001, ...,  0.05293342,
        -1.00563118,  0.90911166],
       ...,
       [ 1.15124883,  1.41704229,  0.79882862, ...,  1.16732114,
         1.42900622,  0.90911166],
       [-0.41952842, -0.72749202, -0.07660001, ...,  0.61012728,
         0.30403584, -1.09997489],
       [ 1.41304503,  1.58200646,  0.79882862, ...,  0.61012728,
         1.78160888,  0.90911166]])

In [54]:
df.describe().T

count        mean         std     min     25%     50%  \
Serial_no          400.0  200.500000  115.614301    1.00  100.75  200.50   
GRE Score          400.0  316.807500   11.473646  290.00  308.00  317.00   
TOEFL Score        400.0  107.410000    6.069514   92.00  103.00  107.00   
University_Rating  400.0    3.087500    1.143728    1.00    2.00    3.00   
SOP                400.0    3.400000    1.006869    1.00    2.50    3.50   
LOR                400.0    3.452500    0.898478    1.00    3.00    3.50   
CGPA               400.0    8.598925    0.596317    6.80    8.17    8.61   
Research           400.0    0.547500    0.498362    0.00    0.00    1.00   
Chance_of_Admit    400.0    0.724350    0.142609    0.34    0.64    0.73   

                        75%     max  
Serial_no          300.2500  400.00  
GRE Score          325.0000  340.00  
TOEFL Score        112.0000  120.00  
University_Rating    4.0000    5.00  
SOP                  4.0000    5.00  
LOR                  4.0000    5.00  
CGPA                 9.0625    9.92  
Research             1.0000    1.00  
Chance_of_Admit      0.8300    0.97

In [56]:
# x=[df.University_Rating,df.SOP,df.LOR,df.CGPA]
# x

In [57]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [58]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [68]:
lr.fit(X_train,y_train)

LinearRegression()

In [69]:
y_pred=lr.predict(X_test)
y_pred

array([0.65117446, 0.72368741, 0.93536809, 0.82164316, 0.58158673,
       0.92863016, 0.52682366, 0.54308993, 0.65940583, 0.83834924,
       0.72008833, 0.90749769, 0.55354476, 0.89008648, 0.70389539,
       0.68664473, 0.66657268, 0.48196096, 0.69057217, 0.97493132,
       0.58802433, 0.65286881, 0.71150098, 0.53528647, 0.94677007,
       0.80982947, 0.69459383, 0.56495613, 0.68192423, 0.81039878,
       0.80796481, 0.94640983, 0.64599494, 0.51104918, 0.65983663,
       0.66907811, 0.71572271, 0.64556878, 0.61540702, 0.87367833,
       0.74275261, 0.59782649, 0.77456683, 0.95944897, 0.85124125,
       0.83554825, 0.94662422, 0.64822919, 0.92247594, 0.85906183,
       0.89624998, 0.72869743, 0.78874783, 0.95142703, 0.57325803,
       0.58744723, 0.68621316, 0.84544646, 0.60495144, 0.84808919,
       0.66642894, 0.65524969, 0.70024808, 0.51206905, 0.62930376,
       0.7173701 , 0.62200838, 0.84170334, 0.85675802, 0.79886217,
       0.72196478, 0.81448203, 0.87373609, 0.83332085, 0.52554

In [70]:
from sklearn.metrics import mean_squared_error
error=mean_squared_error(y_test,y_pred)
error

0.004617003377285012

In [71]:
from sklearn.metrics import r2_score
accuracy=r2_score(y_test,y_pred)
accuracy

0.8212082591486991

In [73]:
from sklearn.neighbors import KNeighborsRegressor
knr=KNeighborsRegressor()
knr.fit(X_train,y_train)

KNeighborsRegressor()

In [79]:
y_pred = knr.predict(X_test)
y_pred

array([0.694, 0.726, 0.926, 0.838, 0.652, 0.934, 0.568, 0.498, 0.61 ,
       0.812, 0.682, 0.918, 0.574, 0.88 , 0.702, 0.692, 0.664, 0.536,
       0.728, 0.942, 0.64 , 0.7  , 0.69 , 0.52 , 0.95 , 0.792, 0.788,
       0.57 , 0.686, 0.82 , 0.78 , 0.93 , 0.682, 0.562, 0.702, 0.65 ,
       0.656, 0.684, 0.606, 0.826, 0.73 , 0.67 , 0.784, 0.952, 0.886,
       0.824, 0.95 , 0.682, 0.932, 0.842, 0.904, 0.702, 0.778, 0.936,
       0.638, 0.634, 0.672, 0.842, 0.652, 0.876, 0.666, 0.644, 0.738,
       0.572, 0.666, 0.696, 0.656, 0.81 , 0.824, 0.752, 0.77 , 0.82 ,
       0.91 , 0.88 , 0.52 , 0.728, 0.724, 0.622, 0.886, 0.734])

In [82]:
knr.score(X_test,y_test)

0.7553997561558545

In [83]:
from sklearn.svm import SVR
avr=SVR()

In [84]:
avr.fit(X_train,y_train)

SVR()

In [85]:
y_pred3=avr.predict(X_test)
y_pred3

array([0.65199602, 0.68602408, 0.85929193, 0.78330002, 0.57831525,
       0.87488605, 0.5806501 , 0.49535393, 0.64237025, 0.81531762,
       0.67353582, 0.86430488, 0.53908087, 0.82884502, 0.65707219,
       0.69197057, 0.65793393, 0.50516699, 0.69060848, 0.87998904,
       0.59951184, 0.65784152, 0.69082807, 0.48452349, 0.89428037,
       0.76466571, 0.69974796, 0.56116604, 0.67822722, 0.78253272,
       0.76272566, 0.8860876 , 0.64862619, 0.50642486, 0.64874266,
       0.63835194, 0.66641976, 0.64480295, 0.58876966, 0.75950202,
       0.72527002, 0.60064176, 0.73055768, 0.88605834, 0.80791804,
       0.80932878, 0.86079372, 0.66916775, 0.87587281, 0.83652031,
       0.85290669, 0.64684265, 0.74215709, 0.88350217, 0.55664298,
       0.57549388, 0.68363031, 0.81531336, 0.61512173, 0.81898425,
       0.66452937, 0.64413775, 0.6947206 , 0.54163542, 0.61707857,
       0.6164698 , 0.61977754, 0.81502905, 0.82774221, 0.77149858,
       0.67504566, 0.72614475, 0.83934652, 0.79726759, 0.49371

In [86]:
avr.score(X_test,y_test)

0.7602850022245242

In [88]:
avr.score(X_test,y_test)

0.7602850022245242

In [91]:
pd.DataFrame([y_test,y_pred])

209   280    33    210   93    84    329   94    266   126  \
Chance_of_Admit  0.68  0.68  0.900  0.79  0.44  0.94  0.43  0.36  0.72  0.85   
Unnamed 0         NaN   NaN  0.562   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

                 ...   320   140    5      45    388   246   227   369  176  \
Chance_of_Admit  ...  0.75  0.84  0.900  0.880  0.49  0.72  0.64  0.67  0.9   
Unnamed 0        ...   NaN   NaN  0.934  0.824   NaN   NaN   NaN   NaN  NaN   

                  289  
Chance_of_Admit  0.79  
Unnamed 0         NaN  

[2 rows x 80 columns]